### PR TITLE
Support Sublime Text 3 + General Overhaul

### PR DESCRIPTION
**Pull request by pykong**
- switched support from ST2 to ST3
- added command for creating new tasks
- updated and beautified README.md
- added command palette entries
- reworked main menu entries

### CODE REVIEW

**Comment by pykong** [comment]
Additional info:
- According to maintainers of SublimeText, the percentage of ST2 users compared to the whole users base is below 2% as of 2017.
- Therefore updating to ST3 will allow mdTodo to benefit 50x the users.
- Those wishing to still use ST2 can install the original plugin **iTodo** which offers almost identical functionality

**Comment by pykong** [comment]
The package control channel needs to be updated accordingly, to reflect the changed compatibility

@groenewege 
I noticed neither **iTODO** nor this plugin has received many updates during the last 5 years.
In case you need a new maintainer, I am gladly taking over it. I maintain a range of other SublimeText plugins already and are actively involved in their development on a daily basis.

**Comment by groenewege** [comment]
Hello,

I don't mind giving you maintainer access to this repo.
How do I go about doing this ?

best regards,
gunther

**Comment by pykong** [comment]
Sure, we could maintain it together.
Thanks for your trust, Gunther!

**Pull request merged**
